# Generated by Django 2.2.6 on 2019-10-23 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_auto_20191023_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('constraint', models.TextField()),
                ('input_desc', models.TextField()),
                ('output_desc', models.TextField()),
                ('sample_input', models.TextField()),
                ('sample_output', models.TextField()),
                ('setter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='problem',
            constraint=models.UniqueConstraint(fields=('title', 'description'), name='problem_identity'),
        ),
    ]
