# Generated by Django 2.2.6 on 2019-10-30 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='category',
        ),
    ]
