# Generated by Django 2.2.6 on 2019-10-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='constraint',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_input',
            field=models.TextField(default='N/A'),
        ),
    ]
