# Generated by Django 2.2.6 on 2019-10-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('profile_img', models.ImageField(upload_to='img/admin_profile_pic')),
                ('passwd', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('profile_img', models.ImageField(upload_to='img/profile_pic')),
                ('passwd', models.CharField(max_length=20)),
                ('rank', models.CharField(max_length=10)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
