# Generated by Django 2.2.6 on 2019-10-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('profile_img', models.ImageField(upload_to='img/admin_profile_pic')),
                ('passwd', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('profile_img', models.ImageField(upload_to='img/profile_pic')),
                ('passwd', models.CharField(max_length=20)),
                ('rank', models.CharField(default='NOOB', max_length=10)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('profile_img', models.ImageField(upload_to='img/profile_pic')),
                ('password', models.CharField(max_length=20)),
                ('user_type', models.CharField(max_length=20)),
                ('rank', models.CharField(default='', max_length=10)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('username', 'user_type'), name='user_identity'),
        ),
    ]
