# Generated by Django 2.2.6 on 2019-10-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='rank',
            field=models.CharField(default='NOOB', max_length=10),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
